
name: Client Side Tools and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose your Python version
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@dbc063f58d05e0c77d55fc905e883e553d5da11b
      - name: Run Codacy Analysis CLI with Custom Registry
        uses: codacy/codacy-analysis-cli-action@dbc063f58d05e0c77d55fc905e883e553d5da11b
        with:
          registry-address: 'test.io'
